GET http://localhost:4004/stats/OrderInfo

### Add some orders
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{"book_id":201, "quantity":4}

### Add some orders
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{"book_id":252, "quantity":7}

### Add some orders
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{"book_id":421, "quantity":12}