GET http://localhost:4004/catalog/Books
###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{"ID":12, "title":"this is my new 12th book: Max Streifeneder"}

###
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{"book_id":421, "quantity":10}
