GET http://localhost:4004/catalog/Books
###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{"id":10, "title":"this is my new book: Max Streifeneder"}

###
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{"book_id":421, "quantity":10}
